### ISSUE TITLE
No Alexa Driver in Repository

### ISSUE THREAD

**Issue by mikemillers** [botman/driver-amazon-alexa#2]
I am following install instructions using botman studio. The command `php artisan botman:install-driver amazon-alexa` gives this error `Unable to find driver "amazon-alexa".`

If I inspect the JSON returned from the repository URL I can see it does not contain the Alexa package.

https://botman.io/studio/drivers.json

**Comment by mpociot** [comment]
Oh right. In the meantime, you can just install it by requiring the composer dependency!

**Comment by mikemillers** [comment]
Yep sure I have done that, thanks a lot!

**Comment by mpociot** [comment]
The driver is now added

**Comment by jszobody** [comment]
I'm getting this same error, and Alex doesn't appear to be in https://botman.io/studio/drivers.json again.
