### ISSUE TITLE
Support AudioPlayer?

### ISSUE THREAD

**Issue by mizansyed** [botman/driver-amazon-alexa#4]
Hi
I recently noticed Botman supports Alexa and got excited!
One thing I cannot find is whether the Alexa driver supports AudioPlayer and DisplayCards. Is this/will be supported?
Thanks in advance for your response

**Comment by mpociot** [comment]
Hi!

Cards are supported, and briefly covered in the documentation: https://botman.io/2.0/driver-amazon-alexa#sending-alexa-cards
The AudioPlayer part is not yet implemented.
